=== Nilphy/moteguardian/config/ionix.dtd
<!ELEMENT acciones (accion*)>
<!ELEMENT accion (nombre,link,modulo,clase)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT modulo (#PCDATA)>
<!ELEMENT clase (#PCDATA)>

<!ELEMENT application (i18n*,authentication)>
<!ELEMENT i18n (file*)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST file language CDATA #REQUIRED>
<!ELEMENT authentication EMPTY>
<!ATTLIST authentication type (bd|ldap) #REQUIRED>

<!ELEMENT datasources (datasource+)>
<!ELEMENT datasource (name,base,hostname,driver,username,password,port)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT hostname (#PCDATA)>
<!ELEMENT driver (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT ldap (hostname,binddn,basedn,bindpw)>
<!ELEMENT binddn (#PCDATA)>
<!ELEMENT basedn (#PCDATA)>
<!ELEMENT bindpw (#PCDATA)>

=== Nilphy/moteguardian/trunk/config/actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE acciones SYSTEM "ionix.dtd">
<acciones>
	<!-- G E N E R A L -->
	<accion>
		<nombre>Login</nombre>
		<link>login</link>
		<modulo>general</modulo>
		<clase>Login</clase>
	</accion>
	<accion>
		<nombre>Inicio</nombre>
		<link>inicio</link>
		<modulo>general</modulo>
		<clase>Inicio</clase>
	</accion>
	<accion>
		<nombre>Logout</nombre>
		<link>logout</link>
		<modulo>general</modulo>
		<clase>Logout</clase>
	</accion>
	<accion>
		<nombre>CambiarPassword</nombre>
		<link>cambiar_pass</link>
		<modulo>general</modulo>
		<clase>CambiarPassword</clase>
	</accion>
	<accion>
		<nombre>AuditoriaAdm</nombre>
		<link>auditoria</link>
		<modulo>general</modulo>
		<clase>AuditoriaAdm</clase>
	</accion>
	<accion>
		<nombre>PermisoDenegado</nombre>
		<link>permiso_denegado</link>
		<modulo>general</modulo>
		<clase>PermisoDenegado</clase>
	</accion>
	<accion>
		<nombre>ConfiguracionSistema</nombre>
		<link>configuracion_sistema</link>
		<modulo>general</modulo>
		<clase>ConfiguracionSistema</clase>
	</accion>	

	<!-- U S U A R I O S -->
	<accion>
		<nombre>UsuarioAlta</nombre>
		<link>usuario_new</link>
		<modulo>usuario</modulo>
		<clase>UsuarioAlta</clase>
	</accion>	
	<accion>
		<nombre>UsuarioMod</nombre>
		<link>usuario_mod</link>
		<modulo>usuario</modulo>
		<clase>UsuarioMod</clase>
	</accion>	
	<accion>
		<nombre>UsuarioBuscar</nombre>
		<link>usuario_adm</link>
		<modulo>usuario</modulo>
		<clase>UsuarioAdm</clase>
	</accion>
	<accion>
		<nombre>UsuarioDel</nombre>
		<link>usuario_del</link>
		<modulo>usuario</modulo>
		<clase>UsuarioDel</clase>
		
	</accion>
	
	<!--CENTRALES-->
	<accion>
		<nombre>CentralAlta</nombre>
		<link>central_new</link>
		<modulo>central</modulo>
		<clase>CentralAlta</clase>
	</accion>
	<accion>
		<nombre>CentralBuscar</nombre>
		<link>central_adm</link>
		<modulo>central</modulo>
		<clase>CentralAdm</clase>
	</accion>
	<accion>
		<nombre>CentralBaja</nombre>
		<link>central_del</link>
		<modulo>central</modulo>
		<clase>CentralDel</clase>
	</accion>
	<accion>
		<nombre>CentralModificar</nombre>
		<link>central_mod</link>
		<modulo>central</modulo>
		<clase>CentralMod</clase>
	</accion>	
	<!--RECOLECTOR FTP-->
	<accion>
		<nombre>RecolectorFTPConf</nombre>
		<link>recolector_FTP_conf</link>
		<modulo>central</modulo>
		<clase>RecolectorFTPConf</clase>
	</accion>
	<accion>
		<nombre>SalidaPopupRecolectorFTP</nombre>
		<link>salida_popup_recolectorFTP</link>
		<modulo>central</modulo>
		<clase>SalidaPopupRecolectorFTP</clase>
	</accion>
	<!--PLANTILLA-->
	<accion>
		<nombre>ValidadorDuplicadosConf</nombre>
		<link>filtro_validador_duplicados</link>
		<modulo>plantilla</modulo>
		<clase>ValidadorDuplicadosConf</clase>
	</accion>
	<accion>
		<nombre>PlantillaConfiguracion</nombre>
		<link>plantilla_configuracion</link>
		<modulo>plantilla</modulo>
		<clase>PlantillaConfiguracion</clase>
	</accion>	
	<accion>
		<nombre>NodoPlantillaRemove</nombre>
		<link>borrar_filtro</link>
		<modulo>plantilla</modulo>
		<clase>NodoPlantillaRemove</clase>
	</accion>
	<accion>
		<nombre>PlantillaAdmin</nombre>
		<link>plantilla_admin</link>
		<modulo>plantilla</modulo>
		<clase>PlantillaAdmin</clase>
	</accion>
	<accion>
		<nombre>PlantillaBaja</nombre>
		<link>plantilla_del</link>
		<modulo>plantilla</modulo>
		<clase>PlantillaBaja</clase>
	</accion>
	<accion>
		<nombre>SalidaPopupValidadorDuplicados</nombre>
		<link>salida_popup_validador_duplicados</link>
		<modulo>plantilla</modulo>
		<clase>SalidaPopupValidadorDuplicados</clase>
	</accion>

	<!--ACTIVIDAD-->
	<accion>
		<nombre>ActividadAlta</nombre>
		<link>actividad_new</link>
		<modulo>actividad</modulo>
		<clase>ActividadAdm</clase>
	</accion>		
	<accion>
		<nombre>ActividadBuscar</nombre>
		<link>actividad_bus</link>
		<modulo>actividad</modulo>
		<clase>ActividadBus</clase>
	</accion>	
	<accion>
		<nombre>ActividadBaja</nombre>
		<link>actividad_del</link>
		<modulo>actividad</modulo>
		<clase>ActividadDel</clase>
	</accion>	
	<accion>
		<nombre>ActividadAdministracion</nombre>
		<link>actividad_adm</link>
		<modulo>actividad</modulo>
		<clase>ActividadAdm</clase>
	</accion>	
	<accion>
		<nombre>ActividadEnvioBaja</nombre>
		<link>actividad_envio_del</link>
		<modulo>actividad</modulo>
		<clase>ActividadEnvioDel</clase>
	</accion>
	<accion>
		<nombre>ActividadEjecutarAhora</nombre>
		<link>actividad_ejecutar_ahora</link>
		<modulo>actividad</modulo>
		<clase>ActividadEjecutarAhora</clase>
	</accion>	
	
	<!--PLANIFICACION-->
	<accion>
		<nombre>PlanificacionConfiguracion</nombre>
		<link>planificacion_configuracion</link>
		<modulo>planificacion</modulo>
		<clase>PlanificacionConfiguracion</clase>
	</accion>		
	<accion>
		<nombre>PlanificacionBaja</nombre>
		<link>planificacion_del</link>
		<modulo>planificacion</modulo>
		<clase>PlanificacionDel</clase>
	</accion>		
	<accion>
		<nombre>SalidaPopupPlanificacion</nombre>
		<link>salida_popup_planificacion</link>
		<modulo>planificacion</modulo>
		<clase>SalidaPopupPlanificacion</clase>
	</accion>
	
	<!-- ENVIADOR FTP -->
	<accion>
		<nombre>EnviadorFTPConf</nombre>
		<link>enviador_FTP_conf</link>
		<modulo>enviador</modulo>
		<clase>EnviadorFTPConf</clase>
	</accion>
	<accion>
		<nombre>SalidaPopupEnviadorFTP</nombre>
		<link>salida_popup_enviadorFTP</link>
		<modulo>enviador</modulo>
		<clase>SalidaPopupEnviadorFTP</clase>
	</accion>
	
	<!-- MONITOREO DE TAREAS -->
	<accion>
		<nombre>MonitoreoTareas</nombre>
		<link>monitoreo_tareas</link>
		<modulo>tareas</modulo>
		<clase>MonitoreoTareas</clase>
	</accion>
	
</acciones>
